import chenImg from './assets/characters/chen.png';
import shihanImg from './assets/characters/shihan.png';
import shuyaImg from './assets/characters/shuya.png';
import laomoImg from './assets/characters/laomo.png';
import maryImg from './assets/characters/mary.png';

export const characters = [
  {
    id: 'chen',
    playable: true,
    name: '陳研究生',
    title: '退件防禦者',
    quote: '我今天不想改論文，我只想活下去。',
    style: '高風險爆發型',
    image: chenImg,
    skills: [
      { id: 'reject', name: 'Reject', desc: '強制退件（高風險）' },
      { id: 'ok', name: 'OK', desc: '偽裝接受（穩定）' },
      { id: 'deadline', name: '最後一天趕稿', desc: '短時間爆發（高代價）' },
    ],
  },
  {
    id: 'shihan',
    playable: true,
    name: '詩涵',
    title: '班導戰士',
    quote: '全部安靜，先解決問題再說。',
    style: '穩定防禦型',
    image: shihanImg,
    skills: [
      { id: 'order', name: '秩序壓制', desc: '穩定局勢' },
      { id: 'teacherAura', name: '班導威壓', desc: '降低危險' },
      { id: 'muscleGuard', name: '肌肉防禦', desc: '硬扛壓力' },
    ],
  },
  {
    id: 'shuya',
    playable: true,
    name: '書雅',
    title: '智慧隊長',
    quote: '理論不夠深，你的論文就像空殼。',
    style: '分析解題型',
    image: shuyaImg,
    skills: [
      { id: 'logic', name: '邏輯分析', desc: '拆解事件' },
      { id: 'review', name: '文獻回顧', desc: '提升成功率' },
      { id: 'reframe', name: '跳脫框架', desc: '低機率神解' },
    ],
  },
  {
    id: 'laomo',
    playable: true,
    name: '老莫',
    title: '叛逆法師',
    quote: '誰想加班？下班時間到了！',
    style: '混亂奇招型',
    image: laomoImg,
    skills: [
      { id: 'void', name: '放空結界', desc: '無視事件' },
      { id: 'offwork', name: '下班時間到了', desc: '強制結束' },
      { id: 'spark', name: '叛逆火花', desc: '未知結果' },
    ],
  },
  {
    id: 'mary',
    playable: false,
    name: '瑪莉教授',
    title: '研究法支配者',
    quote: '好！這週新增二份報告！',
    style: '事件 Boss',
    image: maryImg,
    skills: [
      { id: 'extra', name: '新增作業', desc: '增加壓力' },
      { id: 'observe', name: '深淵觀測', desc: '監控進度' },
      { id: 'pressure', name: '學術壓制', desc: '精神壓迫' },
    ],
  },
];

export const events = [
  {
    id: 'extraHomework',
    title: '瑪莉教授新增作業',
    text: '「好！本週報告從三份變成五份，順便補一份十頁反思。」',
    boss: 'mary',
    bossQuote: '好！這週新增三份報告！',
    best: ['reject'],
    good: ['ok', 'teacherAura', 'offwork'],
    risky: ['deadline', 'spark', 'void'],
  },
  {
    id: 'cameraCrystal',
    title: '深淵顯影水晶錄影',
    text: '瑪莉教授啟動全程錄影，準備把研究成果占為己有。',
    boss: 'mary',
    bossQuote: '好！這叫做教學品質改善！',
    best: ['reject'],
    good: ['logic', 'order', 'offwork'],
    risky: ['void', 'spark'],
  },
  {
    id: 'academicPressure',
    title: '瑪莉教授學術壓制',
    text: '教鞭敲在黑板上，紅色批改痕跡像詛咒一樣爬滿你的論文。',
    boss: 'mary',
    bossQuote: '在我的課堂上，沒有過程，只有標準答案。',
    best: ['teacherAura', 'reject'],
    good: ['muscleGuard', 'logic', 'ok'],
    risky: ['deadline', 'spark'],
  },
  {
    id: 'directionRewrite',
    title: '研究方向突然大修',
    text: '瑪莉教授淡淡說：「這個方向可以全部換掉。」',
    boss: 'mary',
    bossQuote: '好！這部分可以再深入一點。',
    best: ['logic', 'reframe'],
    good: ['review', 'ok'],
    risky: ['reject', 'deadline', 'spark'],
  },
  {
    id: 'theoryBeast',
    title: '理論支持不足之獸',
    text: '遠古巨獸質問：你的研究動機是什麼？理論依據在哪裡？',
    best: ['review'],
    good: ['logic', 'reframe', 'muscleGuard'],
    risky: ['reject', 'spark'],
  },
  {
    id: 'line99',
    title: '611群組99+',
    text: '群組通知瘋狂跳出，玲玲玲學姐又發起了邏輯詭異的投票。',
    best: ['offwork'],
    good: ['void', 'logic', 'order'],
    risky: ['spark', 'deadline'],
  },
  {
    id: 'apaHell',
    title: 'APA格式地獄',
    text: '參考文獻縮排、標點、斜體與年份全部開始反噬。',
    best: ['logic', 'review'],
    good: ['deadline', 'ok'],
    risky: ['reject', 'spark'],
  },
  {
    id: 'methodLost',
    title: '研究法還沒決定',
    text: '量化、質性、行動研究、敘事研究在腦內打成一團。',
    best: ['logic'],
    good: ['review', 'reframe'],
    secret: ['offwork'],
    risky: ['reject', 'deadline'],
  },
  {
    id: 'classChaos',
    title: '課堂秩序失控',
    text: '研究室裡同袍集體精神內耗，討論開始歪樓。',
    best: ['order'],
    good: ['teacherAura', 'muscleGuard', 'logic'],
    risky: ['spark'],
  },
  {
    id: 'proposalCountdown',
    title: '華衫論壇倒數',
    text: '血色沙漏開始倒數，所有人突然意識到計畫書還沒完成。',
    best: ['deadline'],
    good: ['review', 'order', 'void'],
    risky: ['ok', 'spark'],
  },
];

export const resultText = {
  PERFECT: '神解！事件被你用最漂亮的方式破解。',
  PASS: '成功撐過這一週，雖然靈魂有點皺。',
  HARD_PASS: '勉強活下來，但研究室裡的燈又暗了一點。',
  REJECT: '退件成功！不合理的東西被轟回原點。',
  COLLAPSE: '崩潰！你感覺論文正在反過來寫你。',
};
